server:
  port: 8088
spring:
  security:                                        
    user:
      name: carlos
      password: admin
  datasource:
    url: jdbc:postgresql://postgres_server:5432/postgres 
    username: postgres                             
    password: admin                                
    driver-class-name: org.postgresql.Driver       
  jpa:
    hibernate:
      ddl-auto: create-drop                        
    generate-ddl: true
    show-sql: true                                   
        